### ISSUE TITLE
Error when starting prom433: 'socket.gaierror: [Errno -2] Name or service not known'

### ISSUE THREAD

**Issue by mrock99** [andrewjw/prom433#21]
When running 'prom433 --mqtt mqtt://alarm:1883' 
The following error is reported:
-------------------------------
pi@alarm-lr:~ $ prom433 --mqtt mqtt://alarm-lr:1883
Traceback (most recent call last):
  File "/usr/local/bin/prom433", line 4, in <module>
    __import__('pkg_resources').run_script('prom433==2.3.0', 'prom433')
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 666, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1453, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/local/lib/python3.7/dist-packages/prom433-2.3.0-py3.7.egg/EGG-INFO/scripts/prom433", line 60, in <module>
  File "/usr/local/lib/python3.7/dist-packages/prom433-2.3.0-py3.7.egg/EGG-INFO/scripts/prom433", line 53, in main
  File "/usr/local/lib/python3.7/dist-packages/paho_mqtt-1.6.1-py3.7.egg/paho/mqtt/client.py", line 914, in connect
    return self.reconnect()
  File "/usr/local/lib/python3.7/dist-packages/paho_mqtt-1.6.1-py3.7.egg/paho/mqtt/client.py", line 1044, in reconnect
    sock = self._create_socket_connection()
  File "/usr/local/lib/python3.7/dist-packages/paho_mqtt-1.6.1-py3.7.egg/paho/mqtt/client.py", line 3685, in _create_socket_connection
    return socket.create_connection(addr, timeout=self._connect_timeout, source_address=source)
  File "/usr/lib/python3.7/socket.py", line 707, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/usr/lib/python3.7/socket.py", line 748, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known
--------------------------------
Configuration:
PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"

Any help would be appreciated. Thanks.

**Comment by andrewjw** [comment]
Hi, that looks like an error connecting to your MQTT server. I notice in your message you've used both `alarm` and `alarm-lr`. Are they the correct host names, and can you ping them?

**Comment by mrock99** [comment]
Thanks for your reply.

I'm sorry that was a typo of mine in the title for this issue. The command I used is 'prom433 --mqtt mqtt://alarm-lr:1883' (it was correct in the body of the description I wrote).

I am running rtl_433, mqtt and prom433 all on the same Pi (alarm-lr). 

I can run ' mosquitto_sub -h alarm-lr -p 1883' and can see the topics being published from rtl_433. So rtl_433 and mosquitto are working as expected. 

Is the --bind argument used for specifying where to expose the prometheus metrics?

I've tried adding that argument with a random IP and port thinking maybe that was causing the error but it didn't help. 

Maybe I'm not understanding how to invoke prom433 correctly. 

I appreciate your help on this. Your project appears to be exactly what I'm looking for to monitor the temperature of my smoker and graph the data in Grafana.

**Comment by andrewjw** [comment]
Hi,

I'm glad prom433 looks like it will do what you need. Unfortunately I think you're only the third person to use it, so there are definitely still some rough edges.

Yes, --bind specifies which ip and port to expose the Prometheus metrics on. The default is to use all ips and port 9100, so in most cases you shouldn't need to specify it.

What command are you using for rtl_433? Can that connect to the mqtt broker ok? What happens is you use localhost rather than alarm-lr for prom433?

Cheers,
Andrew

**Comment by mrock99** [comment]
I did another download which I assume grabs the latest version however I couldn't find a way for prom433 to report its version. But when looking at the downloaded changelog file the latest version shown is 2.3.1 so I assume that is the one I'm now running.

I did another download which I assume grabs the latest version however I couldn't find a way for prom433 to report its version. But when looking the the downloaded changelog file the latest version shown is 2.3.1 so I assume that is the one I'm now running.

Here are the results using the latest download.
--------------------
pi@alarm-lr:~ $ prom433 --mqtt mqtt://alarm-lr:1883
Traceback (most recent call last):
  File "/usr/local/bin/prom433", line 4, in <module>
    __import__('pkg_resources').run_script('prom433==2.3.0', 'prom433')
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 666, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1453, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/local/lib/python3.7/dist-packages/prom433-2.3.0-py3.7.egg/EGG-INFO/scripts/prom433", line 60, in <module>
  File "/usr/local/lib/python3.7/dist-packages/prom433-2.3.0-py3.7.egg/EGG-INFO/scripts/prom433", line 53, in main
  File "/usr/local/lib/python3.7/dist-packages/paho_mqtt-1.6.1-py3.7.egg/paho/mqtt/client.py", line 914, in connect
    return self.reconnect()
  File "/usr/local/lib/python3.7/dist-packages/paho_mqtt-1.6.1-py3.7.egg/paho/mqtt/client.py", line 1044, in reconnect
    sock = self._create_socket_connection()
  File "/usr/local/lib/python3.7/dist-packages/paho_mqtt-1.6.1-py3.7.egg/paho/mqtt/client.py", line 3685, in _create_socket_connection
    return socket.create_connection(addr, timeout=self._connect_timeout, source_address=source)
  File "/usr/lib/python3.7/socket.py", line 707, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/usr/lib/python3.7/socket.py", line 748, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known
-----------------

Thanks for your assistance Andrew. If I can provide any more information I'd be glad to.

**Comment by andrewjw** [comment]
Hi,

How are you downloading prom433? From the 4th line of your traceback you can see prom433==2.3.0 so I don't think you are running the latest version. `sudo pip3 install prom433==2.3.1` should install the latest version.

What happens if you run `prom433 --mqtt mqtt://localhost:1883`? Is it able to connect then?

Thanks,
Andrew

**Comment by mrock99** [comment]
BTW I am not very experienced using github. So I apologize if that is contributing to these problems.

I get the following error when trying to install 2.3.1
 $ sudo pip3 install prom433==2.3.1
---------------------
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting prom433==2.3.1
  Could not find a version that satisfies the requirement prom433==2.3.1 (from versions: )
No matching distribution found for prom433==2.3.1
--------------------

The result appears to be the same when running 'prom433 --mqtt mqtt://localhost:1883' (using 2.3.0)
-----------------
Traceback (most recent call last):
  File "/usr/local/bin/prom433", line 4, in <module>
    __import__('pkg_resources').run_script('prom433==2.3.0', 'prom433')
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 666, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1453, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/local/lib/python3.7/dist-packages/prom433-2.3.0-py3.7.egg/EGG-INFO/scripts/prom433", line 60, in <module>
  File "/usr/local/lib/python3.7/dist-packages/prom433-2.3.0-py3.7.egg/EGG-INFO/scripts/prom433", line 53, in main
  File "/usr/local/lib/python3.7/dist-packages/paho_mqtt-1.6.1-py3.7.egg/paho/mqtt/client.py", line 914, in connect
    return self.reconnect()
  File "/usr/local/lib/python3.7/dist-packages/paho_mqtt-1.6.1-py3.7.egg/paho/mqtt/client.py", line 1044, in reconnect
    sock = self._create_socket_connection()
  File "/usr/local/lib/python3.7/dist-packages/paho_mqtt-1.6.1-py3.7.egg/paho/mqtt/client.py", line 3685, in _create_socket_connection
    return socket.create_connection(addr, timeout=self._connect_timeout, source_address=source)
  File "/usr/lib/python3.7/socket.py", line 707, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/usr/lib/python3.7/socket.py", line 748, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known
-------------------

**Comment by mrock99** [comment]
Regarding your question about how I had downloaded and installed prom433; I downloaded the zip file from the 'Code' menu  to the Pi and then extracted the files to an empty directory. Then from that directory I ran the following commands:
sudo python3 setup.py build
sudo pythone3 setup.py install

No errors were reported. This installed v2.3.0.

**Comment by mrock99** [comment]
I installed a newer version of python (3.9.0). I think previously I was running 3.7.3.
Now prom433  v2.3.1 appears to have been installed. However it did report this at the end of the install:
'prom433 requires Python '>=3.8' but the running Python is 3.7.3'

Which is strange because 3.9.0 is installed and running.

Anyway now if I run 'prom433 --mqtt mqtt://alarm-lr:1883' I get this:
'Error connecting to mqtt server 'mqtt://alarm-lr:1883': [Errno -2] Name or service not known'

It does the same if I use '//localhost' or if I specify the IP directly.

I know mqtt is running because I can run 'mosquitto_sub -h alarm-lr -p 1883 ...' and see the topic information regularly printed to the console.

**Comment by mrock99** [comment]
I can see the prometheus service running in a browser on the PI on port 9090. I'm not very familiar with prometheus so I could be not configuring something properly.

**Comment by andrewjw** [comment]
Hi,

I'm really sorry, I think this is because I've made a mistake in the documentation. Can you try running `prom433 --mqtt alarm-lr`?

Fingers crossed that will work! If so I'll update the documentation.

Cheers,
Andrew

**Comment by mrock99** [comment]
Success, I think!
------------
$ prom433 --mqtt alarm-lr
Connected with result code 0
127.0.0.1 - - [15/Apr/2023 13:15:39] "GET /metrics HTTP/1.1" 200 -
127.0.0.1 - - [15/Apr/2023 13:15:54] "GET /metrics HTTP/1.1" 200 -
127.0.0.1 - - [15/Apr/2023 13:16:09] "GET /metrics HTTP/1.1" 200 -
----------------------
I can see port 9100 with a status of 'Up' in the prometheus page in my browser. So I think it is working correctly. I will now spend time learning how to import that data into Grafana.

Thanks very much for your assistance Andrew!

**Comment by mrock99** [comment]
Andrew, I am using rtl_433 to send data to an mqtt broker from a temperature sensor and then expecting prom433 to make that data available to prometheus. Is there an easy way for me to view the data being made available from via prom433 to ensure prom433 is working correctly?

**Comment by andrewjw** [comment]
Hi,

Yes, if you visit alarm-lr:9100 in your web browser you should see the metrics it's exposing. This is also the address you should add in the Prometheus config file. It will log information about any metrics it's not set up to handle, so worth checking the logs too.

Have you run rtl_433 without the config to send data to mqtt? Prom433 will only expose data sent by rtl_433, and it doesn't send anything prom433 doesn't have anything to expose. Rtl_433 can be a bit tricky to get working properly.

Cheers,
Andrew
